// Lightweight project templates — data, not an engine (PRD §10). Each
// template seeds phases, starter tasks, milestones and deliverables at
// project creation; everything stays fully editable afterwards.
import type { ProjectTemplate } from "@/types/projects"

export const PROJECT_TEMPLATES: ProjectTemplate[] = [
  {
    id: "topographical",
    name: "Topographical Survey",
    description: "Standard topo survey: control, field capture, processing, plan production.",
    projectType: "Topographical Survey",
    phases: ["Planning", "Data Acquisition", "Processing", "Quality Control", "Map Production", "Delivery"],
    tasks: [
      { name: "Site reconnaissance", phase: "Planning", priority: "High" },
      { name: "Control establishment", phase: "Data Acquisition", priority: "High" },
      { name: "Detail pick-up (total station / GNSS)", phase: "Data Acquisition" },
      { name: "Data download and reduction", phase: "Processing" },
      { name: "Contour modelling", phase: "Processing" },
      { name: "Quality control checks", phase: "Quality Control", priority: "High" },
      { name: "Topographical plan preparation", phase: "Map Production" },
      { name: "Final delivery and briefing", phase: "Delivery" },
    ],
    milestones: [
      { name: "Site visit completed" },
      { name: "Field work completed" },
      { name: "Raw data processed" },
      { name: "Draft plan delivered" },
      { name: "Final plan delivered" },
      { name: "Client approval received" },
    ],
    deliverables: [
      { name: "Topographical Map" },
      { name: "Survey Plan" },
      { name: "Technical Report" },
      { name: "Digital Data (CAD/GIS)" },
    ],
  },
  {
    id: "cadastral",
    name: "Boundary / Cadastral Survey",
    description: "Beacon verification, boundary determination, survey plan for title.",
    projectType: "Boundary/Cadastral Survey",
    phases: ["Planning", "Field Work", "Processing", "Quality Control", "Delivery"],
    tasks: [
      { name: "Title documents and charting review", phase: "Planning", priority: "High" },
      { name: "Beacon search and verification", phase: "Field Work", priority: "High" },
      { name: "Boundary tracing and measurement", phase: "Field Work" },
      { name: "Computation of areas and misclosures", phase: "Processing" },
      { name: "Survey plan drafting", phase: "Processing" },
      { name: "Checks and sign-off", phase: "Quality Control", priority: "High" },
      { name: "Plan delivery", phase: "Delivery" },
    ],
    milestones: [
      { name: "Beacons verified" },
      { name: "Field survey completed" },
      { name: "Computations completed" },
      { name: "Survey plan ready" },
    ],
    deliverables: [
      { name: "Survey Plan" },
      { name: "Coordinate Schedule" },
      { name: "Survey Report" },
    ],
  },
  {
    id: "engineering",
    name: "Engineering Survey",
    description: "Setting-out, monitoring and as-built support for construction.",
    projectType: "Engineering Survey",
    phases: ["Planning", "Field Work", "Processing", "Quality Control", "Delivery"],
    tasks: [
      { name: "Design drawing review", phase: "Planning" },
      { name: "Control transfer to site", phase: "Field Work", priority: "High" },
      { name: "Setting-out / stakeout", phase: "Field Work" },
      { name: "As-built measurements", phase: "Field Work" },
      { name: "Data processing and comparison", phase: "Processing" },
      { name: "Tolerance checks", phase: "Quality Control", priority: "High" },
      { name: "Reports and plans issue", phase: "Delivery" },
    ],
    milestones: [
      { name: "Control established on site" },
      { name: "Setting-out completed" },
      { name: "As-built survey completed" },
      { name: "Report delivered" },
    ],
    deliverables: [
      { name: "Setting-out Plan" },
      { name: "As-built Drawing" },
      { name: "Survey Report" },
    ],
  },
  {
    id: "drone-mapping",
    name: "Drone Mapping",
    description: "UAV flight planning, image acquisition, orthomosaic and DEM production.",
    projectType: "Drone Mapping",
    phases: ["Planning", "Data Acquisition", "Image Processing", "GIS Processing", "Quality Control", "Map Production", "Delivery"],
    tasks: [
      { name: "Flight planning and permits", phase: "Planning", priority: "High" },
      { name: "GCP marking and survey", phase: "Data Acquisition", priority: "High" },
      { name: "UAV flights", phase: "Data Acquisition" },
      { name: "Aerial triangulation", phase: "Image Processing" },
      { name: "Orthomosaic generation", phase: "Image Processing" },
      { name: "DEM/DSM extraction", phase: "GIS Processing" },
      { name: "Accuracy assessment", phase: "Quality Control", priority: "High" },
      { name: "Map and mosaic production", phase: "Map Production" },
      { name: "Final delivery", phase: "Delivery" },
    ],
    milestones: [
      { name: "Flight permissions received" },
      { name: "Flights completed" },
      { name: "Orthomosaic generated" },
      { name: "QC passed" },
      { name: "Deliverables released" },
    ],
    deliverables: [
      { name: "Drone Orthomosaic" },
      { name: "DEM / DSM" },
      { name: "GIS Dataset" },
      { name: "Flight Report" },
    ],
  },
  {
    id: "gis",
    name: "GIS Project",
    description: "Geodatabase design, data capture/compilation and map series output.",
    projectType: "GIS Project",
    phases: ["Planning", "Data Acquisition", "GIS Processing", "Quality Control", "Delivery"],
    tasks: [
      { name: "Requirements and schema design", phase: "Planning", priority: "High" },
      { name: "Data sources inventory", phase: "Planning" },
      { name: "Digitization and attribution", phase: "Data Acquisition" },
      { name: "Spatial analysis", phase: "GIS Processing" },
      { name: "Topology and attribute QC", phase: "Quality Control", priority: "High" },
      { name: "Map series and atlas production", phase: "GIS Processing" },
      { name: "Packaging and delivery", phase: "Delivery" },
    ],
    milestones: [
      { name: "Schema approved" },
      { name: "Data capture completed" },
      { name: "Analysis completed" },
      { name: "Maps approved" },
    ],
    deliverables: [
      { name: "GIS Dataset" },
      { name: "Digital Map" },
      { name: "Metadata Report" },
    ],
  },
  {
    id: "digitization",
    name: "Digitization",
    description: "Paper map/plan scanning, georeferencing and vector conversion.",
    projectType: "Digitization",
    phases: ["Planning", "Digitization", "Quality Control", "Delivery"],
    tasks: [
      { name: "Document inventory and scanning", phase: "Planning" },
      { name: "Georeferencing", phase: "Digitization" },
      { name: "Vector capture", phase: "Digitization" },
      { name: "Attribute entry", phase: "Digitization" },
      { name: "Accuracy checks", phase: "Quality Control", priority: "High" },
      { name: "Output packaging", phase: "Delivery" },
    ],
    milestones: [
      { name: "Scanning completed" },
      { name: "Vector capture completed" },
      { name: "QC passed" },
    ],
    deliverables: [
      { name: "GIS Dataset" },
      { name: "Digital Map" },
    ],
  },
  {
    id: "hydrographic",
    name: "Hydrographic Survey",
    description: "Bathymetric capture, tide/level reduction and chart production.",
    projectType: "Hydrographic Survey",
    phases: ["Planning", "Data Acquisition", "Processing", "Quality Control", "Delivery"],
    tasks: [
      { name: "Sounding plan design", phase: "Planning" },
      { name: "Tide/level station setup", phase: "Data Acquisition", priority: "High" },
      { name: "Bathymetric data capture", phase: "Data Acquisition" },
      { name: "Sound velocity and reductions", phase: "Processing" },
      { name: "Surface model and contours", phase: "Processing" },
      { name: "Crossline QC", phase: "Quality Control", priority: "High" },
      { name: "Chart/plan production", phase: "Delivery" },
    ],
    milestones: [
      { name: "Field capture completed" },
      { name: "Data reduced" },
      { name: "QC passed" },
      { name: "Chart delivered" },
    ],
    deliverables: [
      { name: "Bathymetric Chart" },
      { name: "Surface Model" },
      { name: "Survey Report" },
    ],
  },
  {
    id: "training",
    name: "Training",
    description: "Short-course delivery: materials, sessions, assessment, certificates.",
    projectType: "Training",
    phases: ["Planning", "Preparation", "Delivery", "Completion"],
    tasks: [
      { name: "Curriculum and materials", phase: "Preparation", priority: "High" },
      { name: "Venue and logistics", phase: "Preparation" },
      { name: "Sessions delivered", phase: "Delivery" },
      { name: "Assessments", phase: "Delivery" },
      { name: "Certificates and report", phase: "Completion" },
    ],
    milestones: [
      { name: "Materials ready" },
      { name: "Sessions completed" },
      { name: "Assessments done" },
    ],
    deliverables: [
      { name: "Training Report" },
      { name: "Certificates" },
    ],
  },
]

export function templateById(id: string): ProjectTemplate | null {
  return PROJECT_TEMPLATES.find((t) => t.id === id) || null
}
